#####################
# Custom Exceptions #
#####################

class InstanceNotFound(Exception): ...

class EnvironmentMalformed(Exception): ...

class EnvironmentNotFound(Exception): ...

class WrongAction(Exception): ...
